# Generated by Django 5.1.7 on 2025-03-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[ ('half_face', 'Half Face Helmet'),('modular', 'Modular Helmet'),('open_face', 'Open Face Helmet'),('sports', 'Sports Helmet'),('motorcross', 'Motocross Helmet'),('visor', 'Helmet Visor'),('accessories', 'Helmet Accessories'),('racing', 'Racing Helmet'),('cruiser', 'Cruiser Helmet'),('scooter', 'Scooter Helmet'),('kids', 'Kids Helmet'),], max_length=50)),
                ('image', models.FileField(upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
