# Generated by Django 3.2 on 2025-04-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20250424_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.CharField(default='standard', max_length=50),
        ),
    ]
