# Generated by Django 3.2 on 2025-04-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20250424_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
    ]
