# Generated by Django 5.2 on 2025-04-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_cart_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
    ]
